### ISSUE TITLE
create a metrics watcher

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#1007]
Create a way to gather metrics:

```yaml
name: extractorMetrics
version: 0.0.1
initial_state: gather

transitions:
  - name: maintenance
    destination: pause
    from:
      - gather

  - name: resume
    destination: gather
    from:
      - pause

watchers:
  - name: metrics
    type: metric
    state_match:
      - gather
    properties:
      command: /home/rip/bin/kasa-plug --plug dehumidifier-plug.example.net energy --choria
      interval: 1m
```

The command has to output data like, all values are float64:

```json
{
  "labels": {
    "address": "dehumidifier-plug.example.net",
    "alias": "Dehumidifier",
    "id": "8006B2F62F673091ED1A642C0B5AA7541B26675C",
    "model": "HS110(UK)"
  },
  "metrics": {
    "current_amp": 2.4609999656677246,
    "on_seconds": 939,
    "power_state": 1,
    "power_w": 570.6669921875,
    "total_w": 1138.4830322265625,
    "voltage_v": 233.05099487304688
  }
}
```

This will emit an event with the metric that Tally should later gather and expose to prometheus
