### ISSUE TITLE
Add coordinated max concurrent runs to the exec watcher

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#1276]
I want to be able to replace `mco puppet runall` using auto agent.

So an exec watcher should support like:

```
- name: run_puppet
  type: exec
  interval: 1h
  state_match:
  - RUN
  properties:
    command: "./puppet_test.sh"
    suppress_success_announce: true
    timeout: 5m
    governor: puppet
```

By adding `governor: puppet` all these exec watchers will coordinate around a system that controls the network wide concurrency of these command executions.

We set the interval high so that for an entire hour it will try to find a slot in the governor and if it does it will run puppet and that puppet run will have 5 minutes to complete.

We should have a CLI tool to assist in the creation of the stream accordingly, or perhaps at startup of this watcher it should try to LoadOrCreate the stream in question though that's dangerous.

Using the technique shown here: https://www.youtube.com/watch?v=VFWip_rkzTs
