### ISSUE TITLE
machine validate fails

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#1974]
This appears to be a valid machine.yaml but validate doesnt like it at all

```yaml
name: thing
version: 1.27.5
initial_state: INITIAL

transitions:
  - name: enter_maintenance
    destination: MAINTENANCE
    from:
      - INITIAL
      - CLEANUP

  - name: resume
    destination: INITIAL
    from:
      - MAINTENANCE

  - name: start_schedule
    destination: CLEANUP
    from:
      - INITIAL

  - name: immediate_gather
    destination: INITIAL
    from:
      - CLEANUP

watchers:
  - name: splay
    type: timer
    fail_transition: start_schedule
    state_match:
      - INITIAL
    properties:
      splay: true
      timer: 1m

  - name: maintenance_timeout
    type: timer
    fail_transition: resume
    state_match:
      - MAINTENANCE
    properties:
      timer: 24h

  - name: cleanup_jobrunner_logs
    type: exec
    interval: 24h
    state_match:
      - CLEANUP
    properties:
      suppress_success_announce: false
      timeout: 1m
      gather_initial_state: true
      command: ./thing cleanup
```

```
$ choria machine validate .
/watchers/0: anyOf failed
/watchers/0: doesn't validate with '/definitions/WatcherFile'
/watchers/0/type: value must be "file"
/watchers/0/properties: doesn't validate with '/definitions/WatcherFileProperties'
/watchers/0/properties: missing properties: 'path'
/watchers/0: doesn't validate with '/definitions/WatcherExec'
/watchers/0/properties: doesn't validate with '/definitions/WatcherExecProperties'
/watchers/0/properties: missing properties: 'command'
/watchers/0/type: value must be "exec"
/watchers/0: doesn't validate with '/definitions/WatcherNagios'
/watchers/0/properties: doesn't validate with '/definitions/WatcherNagiosProperties'
/watchers/0/properties: missing properties: 'plugin'
/watchers/0/type: value must be "nagios"
/watchers/0: doesn't validate with '/definitions/WatcherSchedule'
/watchers/0/properties: doesn't validate with '/definitions/WatcherScheduleProperties'
/watchers/0/properties: missing properties: 'duration', 'schedules'
/watchers/0/type: value must be "schedule"
/watchers/0: doesn't validate with '/definitions/WatcherHomekit'
/watchers/0/properties: doesn't validate with '/definitions/WatcherHomeKitProperties'
/watchers/0/properties: missing properties: 'pin'
/watchers/0/type: value must be "schedule"
/watchers/0: doesn't validate with '/definitions/WatcherTimer'
/watchers/0/type: value must be "schedule"
/watchers/0: doesn't validate with '/definitions/WatcherMetric'
/watchers/0/properties: doesn't validate with '/definitions/WatcherMetricProperties'
/watchers/0/properties: missing properties: 'command', 'interval'
/watchers/0/type: value must be "schedule"
/watchers/0: doesn't validate with '/definitions/WatcherKV'
/watchers/0/type: value must be "kv"
/watchers/0/properties: doesn't validate with '/definitions/WatcherKVProperties'
/watchers/0/properties: missing properties: 'bucket'
/watchers/1: anyOf failed
/watchers/1: doesn't validate with '/definitions/WatcherFile'
/watchers/1/type: value must be "file"
/watchers/1/properties: doesn't validate with '/definitions/WatcherFileProperties'
/watchers/1/properties: missing properties: 'path'
/watchers/1: doesn't validate with '/definitions/WatcherExec'
/watchers/1/properties: doesn't validate with '/definitions/WatcherExecProperties'
/watchers/1/properties: missing properties: 'command'
/watchers/1/type: value must be "exec"
/watchers/1: doesn't validate with '/definitions/WatcherNagios'
/watchers/1/properties: doesn't validate with '/definitions/WatcherNagiosProperties'
/watchers/1/properties: missing properties: 'plugin'
/watchers/1/type: value must be "nagios"
/watchers/1: doesn't validate with '/definitions/WatcherSchedule'
/watchers/1/properties: doesn't validate with '/definitions/WatcherScheduleProperties'
/watchers/1/properties: missing properties: 'duration', 'schedules'
/watchers/1/type: value must be "schedule"
/watchers/1: doesn't validate with '/definitions/WatcherHomekit'
/watchers/1/properties: doesn't validate with '/definitions/WatcherHomeKitProperties'
/watchers/1/properties: missing properties: 'pin'
/watchers/1/type: value must be "schedule"
/watchers/1: doesn't validate with '/definitions/WatcherTimer'
/watchers/1/type: value must be "schedule"
/watchers/1: doesn't validate with '/definitions/WatcherMetric'
/watchers/1/properties: doesn't validate with '/definitions/WatcherMetricProperties'
/watchers/1/properties: missing properties: 'command', 'interval'
/watchers/1/type: value must be "schedule"
/watchers/1: doesn't validate with '/definitions/WatcherKV'
/watchers/1/type: value must be "kv"
/watchers/1/properties: doesn't validate with '/definitions/WatcherKVProperties'
/watchers/1/properties: missing properties: 'bucket'
FATA[0000] Could not run Choria: validation failed
```
