### ISSUE TITLE
Allow machine transitions as a result of other machines on the node

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#2223]
Transitions in a machine should be able to subscribe to transitions from other machines:

```
transitions:
  - name: to_healthcheck
    from: [unknown]
    destination: one
    subscribe:
      - machine_name: other
        event: to_healthcheck
```

Here if the `other` machine fires a `to_healthcheck ` event then this machine will also fire its `to_healthcheck` event.

This allows for soft reactions to be configured but its not a dependency, the machine will still run and work even if the `other` machine does not even exist.

It's just a way to transition
