### ISSUE TITLE
Allow watchers to require a foreign machine has a certain state

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#2225]
Watchers should be able to do like:

```yaml
require_machine_state:
  - name: other
    state: ok
```

The listed foreign machines (on the same node) should then be in the noted state before the particular watcher will become active, in addition to the existing `state_match` list
