### ISSUE TITLE
support time based watchers

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#591]
There should be watchers that trigger state changes based on something cron like or just start/end times.

Scheduled based example:

```yaml
 - name: scheduler
   type: schedule
   fail_transition: stop
   success_transition: start
   state_match: [switched_on, switched_off]
   properties:
     duration: 1h
     schedules:
       - "0 8 * * *"
       - "0 12 * * *"
       - "0 17 * * *"
```
