### ISSUE TITLE
support running nagios checks in machines

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#895]
A autonomous agent like this should monitor and remediate a service, emit cloud events and be able to be extended with other hooks

```yaml
name: check_httpd
version: 1.0.0
initial_state: unknown

watchers:
  # checks regularly and transitions between OK, WARNING, CRITICAL and UNKNOWN
  - name: check
    type: nagios
    interval: 120s
    state_match: [unknown, ok, warning, critical]
    properties:
      plugin: /usr/lib64/nagios/plugins/check_procs
      args:
        - "-C"
        - "httpd"
        - "-c"
        - "1:25"

  # when critical remediates the service once every 10 minutes, during this state
  # checks will happen as normal so it should transition to OK after a while on its own
  # just be sure to set interval here more than check frequency
  - name: remediate
    type: exec
    state_match: [critical]
    interval: 10m
    properties:
      command: /sbin/service httpd restart

transitions:
  - name: UNKNOWN
    from: [unknown, ok, warning, critical]
    destination: unknown

  - name: OK
    from: [unknown, ok, warning, critical]
    destination: ok

  - name: WARNING
    from: [unknown, ok, warning, critical]
    destination: warning

  - name: CRITICAL
    from: [unknown, ok, warning, critical]
    destination: critical

  # when the machine is transitioned via MAINTENANCE checks will not happen
  - name: MAINTENANCE
    from: [unknown, ok, warning, critical]
    destination: maintenance

  # during maintenance RESUME transition sends it back to unknown for normal checking
  - name: RESUME
    from: [maintenance]
    destination: unknown
```

States should also be written to prometheus text file exporter:

```nohighlight
$ cat  /var/lib/node_exporter/textfile/choria_machine_nagios_watcher_status.prom
# HELP choria_machine_nagios_watcher_status Choria Nagios Check Status
# TYPE choria_machine_nagios_watcher_status gauge
choria_machine_nagios_watcher_status{name="check_httpd"} 0
choria_machine_nagios_watcher_status{name="check_bacula_db"} 0
# HELP choria_machine_nagios_watcher_last_run_seconds Choria Nagios Check Time
# TYPE choria_machine_nagios_watcher_last_run_seconds gauge
choria_machine_nagios_watcher_last_run_seconds{name="check_httpd"} 1592645406
choria_machine_nagios_watcher_last_run_seconds{name="check_bacula_db"} 1592645405
```

The puppet module should have a defined type to create these machines
