### ISSUE TITLE
add a kind of builtin nagios check ability that sends heartbeats

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#915]
something like:

```yaml
name: heartbeat
type: nagios
interval: 1m
state_match: [....]
properties:
  builtin: heartbeat
```

mainly this will generate heartbeat events
