### ISSUE TITLE
Add a homekit "button" watcher

### ISSUE THREAD

**Issue by ripienaar** [choria-io/go-choria#999]
Use https://github.com/brutella/hc to create a button watcher that switches state based on homekit interaction.

Ideally the choria instance is a bridge with multiple devices, but looks like dynamically adding accessories isnt working so each watcher might need to be a standalone accessory.

Should allow these to be configured:

```go
accessory.Info{
    Name: "Lamp",
    SerialNumber: "051AC-23AAM1",
    Manufacturer: "Apple",
    Model: "AB",
    FirmwareRevision: "1.0.1",
}
```

With `FirmwareRevision` equaling the version of the machine, Name the name of the machine, Manufacturer "Choria", PIN and SetupId should also be configured.

**Comment by ripienaar** [comment]
```yaml
watchers:
   - name: choria_switch
     type: homekit
     state_match: [unknown, "on", "off"]
     success_transition: switch_on
     fail_transition: switch_off
     properties:
       pin: "12345679"
       # make sure the switch is reported as on after restart of choria
       initial: on
       # these listen for rpc based transitions of the machine and map those to on/off in the switch
       on_when: ["on"]
       off_when: ["off"]
       # this outright stops the hk listener when in maintenance mode for example to prevent ppl from pressing buttons
       disable_when: [maintenance]

```
